<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php 
          $_code = $this->getMethodCode();
          $_standardPD = Mage::getSingleton('checkoutapi/standard');
          
          $totals = Mage::getSingleton('checkout/session')->getQuote()->collectTotals();  
          //$shippingAmount = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingAmount();  
          $strTcPaymentMethods = $_standardPD->getConfigData("tcPaymentMethods");
          
          if($strTcPaymentMethods == "" || $strTcPaymentMethods == null){
              $tcPaymentMethods = explode(",","3,4,2,5,18,16,15,19,14,7,22,23,6");
          }else{
              $tcPaymentMethods = explode(",",$strTcPaymentMethods);
          }
    ?>
    <style>
        ul li.tcPaymentMethod{
            float: left;
            padding: 5px;
            width: 80px;
            height: 30px;
        }
        ul li input{
            float: left;
            margin-right: 5px;
        }
        ul li span.tcPaymentFlag{
            float: left;
            width: 60px;
            height: 50px;
            background-image: url(<?php echo $this->getSkinUrl('tray/checkoutapi/images/paymentFlags1.png'); ?>);
            background-repeat: no-repeat;
        }
        /* Diners */
        ul li span.tcPaymentFlag2{
            background-position: -184px -8px;
        }
        /* Visa */
        ul li span.tcPaymentFlag3{
            background-position: 1px -8px;
        }
        /* Master */
        ul li span.tcPaymentFlag4{
            background-position: -60px -8px;
        }
        /* Amex */
        ul li span.tcPaymentFlag5{
            background-position: -123px -8px;
        }
        /* Boleto */
        ul li span.tcPaymentFlag6{
            background-position: -556px -8px;
        }
        /* Itaú */
        ul li span.tcPaymentFlag7{
            background-position: -618px -8px;
        }
        /* Peela */
        ul li span.tcPaymentFlag14{
            background-position: -369px -8px;
        }
        /* Discover */
        ul li span.tcPaymentFlag15{
            background-position: -308px -8px;
        }
        /* Elo */
        ul li span.tcPaymentFlag16{
            background-position: -246px -8px;
        }
        /* Aura */
        ul li span.tcPaymentFlag18{
            background-position: -431px -8px;
        }
        /* JCB */
        ul li span.tcPaymentFlag19{
            background-position: -494px -8px;
        }
        /* Bradesco */
        ul li span.tcPaymentFlag22{
            background-position: -679px -8px;
        }
        /* Banco do Brasil */
        ul li span.tcPaymentFlag23{
            background-position: -741px -8px;
        }
    </style>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        
        <li class="forma_pagamento" style="float:left;;">
            <ul>
                <li>
                    <label for="tcPaymentMethod"><?php echo Mage::helper('payment')->__('Selecione a forma de pagamento') ?> <span class="required">*</span></label><br/>
                    <input type="hidden" id="tcPaymentMethod" name="payment[cc_type]" class="required-entry" value=""/>
                    <ul>
                    <?php
                        foreach ($tcPaymentMethods as $idTcPayment){
                            $displayCcInfo = "none";
                            if(!in_array($idTcPayment, array("6","7","14","22","23"))){
                                $displayCcInfo = "block";
                            }
                    ?>
                        <li class="tcPaymentMethod">
                            <input type="radio" name="tcPaymentMethodR" value="<?php echo $idTcPayment;?>" onclick="document.getElementById('tcPaymentMethod').value = this.value; document.getElementById('displayCcInfo').style.display = '<?php echo $displayCcInfo;?>'"/>
                            <span class="tcPaymentFlag tcPaymentFlag<?php echo $idTcPayment;?>">
                                &nbsp;
                            </span>
                        </li>
                    <?php

                        }
                    ?>
                    </ul>
                </li>
            </ul>
        </li>
        <li id="displayCcInfo" style="display: none;">
            <ul>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner') ?>"/>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
                        <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <input type="hidden" id="<?php echo $_code ?>_split_value" name="payment[traycheckout_split_value]" value="<?php echo $this->getInfoData('traycheckout_split_value')?>"/>
                        <label for="<?php echo $_code ?>_split"><?php echo Mage::helper('payment')->__('Parcelas') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_split" style="width:140px;" name="payment[traycheckout_split_number]" class="required-entry" onchange="document.getElementById('<?php echo $_code ?>_split_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,/,'.');">
                        <?php $_ccSplitSimulator = $this->getInfoData('traycheckout_split_number') ?>
                        <?php foreach ($this->getSplitSimulate($totals->grand_total) as $k=>$v): ?>
                            <option value="<?php echo $k ?>" <?php if($k==$_ccSplitSimulator): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                        </div>
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
</fieldset>